/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/full_ct_head_point_cloud--visible_human_female.glb -T 
Files: public/full_ct_head_point_cloud--visible_human_female.glb [208.11MB] > /Users/flatironschool/Development/projects--2024/point-cloud-segmentation-demo/full_ct_head_point_cloud--visible_human_female-transformed.glb [208.04MB] (0%)
Author: Terrie (https://sketchfab.com/terrielsimmons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/full-ct-head-point-cloud-visible-human-female-76115e69f3304172835cfce7cc6714a8
Title: Full CT Head Point Cloud--Visible Human Female
*/

import React, { useRef, useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF, useTexture } from '@react-three/drei'
import { useControls } from 'leva'


export default function CtScanHead(props) {
	// const glb = useGLTF(process.env.PUBLIC_URL + '/assets/full_ct_head_point_cloud--visible_human_female.glb')
	const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/assets/full_ct_head_point_cloud--visible_human_female.glb')

	const sprite = useTexture(process.env.PUBLIC_URL + '/assets/textures/circle.png')

	const model = useRef()

	// useEffect(() => {
	// 	console.log('%cnodes', 'color:red;font-size:14px;', nodes)
	// }, [nodes])

	useEffect(() => {
		if (!model.current) return

		let object = model.current
		console.log('%cmaterials', 'color:red;font-size:14px;', materials)

		// console.log('%cobject', 'color:red;font-size:14px;', object)

		object.updateMatrixWorld() // donmccurdy/three-gltf-viewer#330

		const box = new THREE.Box3().setFromObject(object)
		// const size = box.getSize(new THREE.Vector3()).length()
		const center = box.getCenter(new THREE.Vector3())

		// this.controls.reset()

		object.position.x -= center.x
		object.position.y -= center.y
		object.position.z -= center.z
	}, [model])

		const scanMaterial = useControls(
			'Scan Material',
			{
				alphaTest: {
					label: 'alphaTest',
					value: 0,
					min: 0,
					max: 1,
				},
			},
			{
				color: 'red',
			}
		)

	return (
		<group {...props} dispose={null}>
			{/* <primitive ref={model} object={glb.scene} /> */}
			<group ref={model} rotation={[-Math.PI / 2, 0, 0]} 
			// scale={0.2}
			>
				<points
					geometry={nodes.Object_2.geometry}
					material={materials['Scene_-_Root']}
					// material-depthWrite={true}
					// material-depthTest={false}
					// material-blending={THREE.AdditiveBlending}
					// material-transparent={true}
					// material-alphaTest={scanMaterial.alphaTest}
					// material-map={sprite}
					// material-size={15}
					// material-vertexColors={true}
				/>
				<points geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_9.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_11.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_12.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_13.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_14.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_15.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_17.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_18.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_19.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_20.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_21.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_22.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_23.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_24.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_25.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_26.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_27.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_28.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_29.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_30.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_31.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_32.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_33.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_34.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_35.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_36.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_37.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_38.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_39.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_40.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_41.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_42.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_43.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_44.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_45.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_46.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_47.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_48.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_49.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_50.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_51.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_52.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_53.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_54.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_55.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_56.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_57.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_58.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_59.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_60.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_61.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_62.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_63.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_64.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_65.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_66.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_67.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_68.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_69.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_70.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_71.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_72.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_73.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_74.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_75.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_76.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_77.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_78.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_79.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_80.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_81.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_82.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_83.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_84.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_85.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_86.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_87.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_88.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_89.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_90.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_91.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_92.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_93.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_94.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_95.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_96.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_97.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_98.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_99.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_100.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_101.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_102.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_103.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_104.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_105.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_106.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_107.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_108.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_109.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_110.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_111.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_112.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_113.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_114.geometry} material={materials['Scene_-_Root']} />
				<points geometry={nodes.Object_115.geometry} material={materials['Scene_-_Root']} />
			</group>
			{/* <points ref={model} geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} /> */}
		</group>
	)
}

useGLTF.preload(process.env.PUBLIC_URL + '/assets/full_ct_head_point_cloud--visible_human_female.glb')
