/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/simple_test.glb 
Author: Snailpot MaysaChan (https://sketchfab.com/snailpot_maysachan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-red-among-us-imposter-b13f848036194a38901852396e8f91b1
Title: Simple Red Among Us IMPOSTER
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SimpleTest(props) {
	const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/assets/simple_test.glb')
	return (
		<group {...props} dispose={null}>
			<mesh scale={0.5} geometry={nodes.PolySphere_PolySphere_0.geometry} material={materials.PolySphere} />
		</group>
	)
}

useGLTF.preload(process.env.PUBLIC_URL + '/assets/simple_test.glb')
